import re
import secrets
from datetime import datetime, timedelta
from typing import Any

from fastapi import APIRouter, Depends, HTTPException
from pydantic import BaseModel
from sqlalchemy.orm import Session

from ..auth import get_current_user
from ..database import get_db
from ..models import AnalysisRecord, SharedReport, User

router = APIRouter(prefix="/share", tags=["share"])

EMAIL_RE = re.compile(r"([A-Za-z0-9._%+-])[A-Za-z0-9._%+-]*@([A-Za-z0-9.-]+\.[A-Za-z]{2,})")
PHONE_RE = re.compile(r"\b(?:\+?\d{1,3}[\s.-]?)?(?:\(?\d{3}\)?[\s.-]?)\d{3}[\s.-]?\d{4}\b")


class CreateShareRequest(BaseModel):
    analysis_id: int
    expires_in_days: int = 7


class RevokeShareRequest(BaseModel):
    token: str


def mask_pii(value: Any) -> Any:
    if isinstance(value, dict):
        return {k: mask_pii(v) for k, v in value.items()}
    if isinstance(value, list):
        return [mask_pii(v) for v in value]
    if isinstance(value, str):
        value = EMAIL_RE.sub(lambda m: f"{m.group(1)}***@{m.group(2)}", value)
        value = PHONE_RE.sub("***-***-****", value)
    return value


@router.post("/create")
def create_share(
    payload: CreateShareRequest,
    current_user: User = Depends(get_current_user),
    db: Session = Depends(get_db),
):
    analysis = (
        db.query(AnalysisRecord)
        .filter(AnalysisRecord.id == payload.analysis_id, AnalysisRecord.owner_user_id == current_user.id)
        .first()
    )
    if not analysis:
        raise HTTPException(status_code=404, detail="Analysis not found")

    expires_days = min(30, max(1, int(payload.expires_in_days or 7)))
    token = secrets.token_urlsafe(32)
    rec = SharedReport(
        owner_user_id=current_user.id,
        analysis_id=analysis.id,
        token=token,
        expires_at=datetime.utcnow() + timedelta(days=expires_days),
        created_at=datetime.utcnow(),
    )
    db.add(rec)
    db.commit()
    db.refresh(rec)
    return {
        "token": token,
        "share_url": f"/shared/{token}",
        "expires_at": rec.expires_at.isoformat(),
    }


@router.post("/revoke")
def revoke_share(
    payload: RevokeShareRequest,
    current_user: User = Depends(get_current_user),
    db: Session = Depends(get_db),
):
    rec = db.query(SharedReport).filter(SharedReport.token == payload.token, SharedReport.owner_user_id == current_user.id).first()
    if not rec:
        raise HTTPException(status_code=404, detail="Share token not found")
    db.delete(rec)
    db.commit()
    return {"ok": True}


@router.get("/{token}")
def read_share(token: str, db: Session = Depends(get_db)):
    rec = db.query(SharedReport).filter(SharedReport.token == token).first()
    if not rec:
        raise HTTPException(status_code=404, detail="Invalid token")
    if rec.expires_at < datetime.utcnow():
        raise HTTPException(status_code=410, detail="Share link expired")

    analysis = db.query(AnalysisRecord).filter(AnalysisRecord.id == rec.analysis_id).first()
    if not analysis:
        raise HTTPException(status_code=404, detail="Analysis not found")

    masked = mask_pii(dict(analysis.result_json or {}))
    return {
        "analysis": masked,
        "expires_at": rec.expires_at.isoformat(),
        "watermark": "Generated by TalentAlign AI (Demo)",
    }