import { useEffect, useState } from "react";
import { useParams } from "react-router-dom";
import { motion } from "framer-motion";

import api from "../lib/api";

export default function SharedReport() {
  const { token } = useParams();
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState("");
  const [analysis, setAnalysis] = useState<any>(null);

  useEffect(() => {
    const load = async () => {
      try {
        const { data } = await api.get(`/share/${token}`);
        setAnalysis(data.analysis);
        setError("");
      } catch (err: any) {
        setError(err?.response?.data?.detail || "Failed to load shared report.");
      } finally {
        setLoading(false);
      }
    };
    load();
  }, [token]);

  if (loading) return <main className="mx-auto max-w-5xl px-4 pt-16">Loading...</main>;
  if (error) return <main className="mx-auto max-w-5xl px-4 pt-16 text-rose-700 dark:text-rose-300">{error}</main>;

  return (
    <motion.main initial={{ opacity: 0 }} animate={{ opacity: 1 }} className="mx-auto max-w-5xl space-y-4 px-4 pb-16 pt-8">
      <div className="glass rounded-card p-4 shadow-soft">
        <p className="text-xs uppercase tracking-wide text-[var(--text-muted)]">Generated by TalentAlign AI (Demo)</p>
        <h1 className="mt-1 text-2xl font-extrabold">Shared Read-Only Report</h1>
      </div>
      <div className="glass rounded-card p-4 shadow-soft">
        <p className="text-lg font-bold">Score: {analysis.score}%</p>
        <p className="text-sm text-[var(--text-muted)]">Mode: {analysis.analysis_mode}</p>
      </div>
      <div className="glass rounded-card p-4 shadow-soft">
        <h3 className="mb-2 font-bold">Overlapping Skills</h3>
        <p className="text-sm">{(analysis.overlapping_skills || []).join(", ") || "-"}</p>
      </div>
      <div className="glass rounded-card p-4 shadow-soft">
        <h3 className="mb-2 font-bold">Missing Skills</h3>
        <p className="text-sm">{(analysis.missing_skills || []).join(", ") || "-"}</p>
      </div>
    </motion.main>
  );
}